### ISSUE TITLE
[BUG] Plugin installed correctly, keybinds refuse to work

### ISSUE THREAD

**Issue by Fxzzi** [joshskidmore/zsh-fzf-history-search#22]
Hi there! I've installed this plugin using zgenom, however I am unable to use it as the keybinding isn't working. I also had this issue with [https://github.com/zsh-users/zsh-history-substring-search](url) and I had to use their alternative keybinding setup as shown in their README.md. 
![](https://cdn.upload.systems/uploads/GPrybdF0.png)

I'm wondering now what I can do to make this work. I am using zsh with the kitty terminal.

**Comment by joshskidmore** [comment]
I don't personally use zgenom, but from the suggestion mentioned on the zsh-users/zsh-history-substring-search README, you may try **after** loading this plugin:

```sh
bindkey "$terminfo[kcuu1]" fzf_history_search
bindkey "$terminfo[kcud1]" fzf_history_search
```
