### ISSUE TITLE
[Question or Feature] Keep the search term if none of the history results is selected

### ISSUE THREAD

**Issue by oatmealb** [joshskidmore/zsh-fzf-history-search#23]
Thanks for this great plugin. I have the following usage question, potentially a feature request:

**Case**: you search for `foo` and the only history item you have is `bar`.
**Desired outcome**: you are able to keep `foo` after exiting this plugin. Or, additionally, able to _execute_ `foo` directly from the plugin, without exiting it.
**Current outcome**: you are forced to exit the plugin and lose the entered search term `foo` - the longer `foo` is, the worse the outcome.

Is the **Desired outcome** achievable, either by this plugin or by [fzf] itself? 
- None of the options in `man fzf` seem applicable. 
- [An issue in **fzf** repo](https://github.com/junegunn/fzf/issues/2995) uses the term "search buffer". It seems that the fzf author's reply implies the **Desired outcome** isn't currently achievable? If so, then feel free to close this issue.

If this is not achievable, but could be within this plugin, please consider this a feature request.

**Comment by joshskidmore** [comment]
Thanks for the suggestion. Unfortunately, I don't think this would be achievable within this plugin - mainly due to fzf.
