### ISSUE TITLE
Doesn't respect fzf environment variables

### ISSUE THREAD

**Issue by cohml** [joshskidmore/zsh-fzf-history-search#33]
It has been raised elsewhere (#31) that this plugin is not sourced properly by Oh My Zsh. So users must manually source `zsh-fzf-history-search.zsh` for it to have any effect.

However, once sourced, it overrides (or probably more accurately, just doesn't use) fzf's own `FZF_CTRL_R_OPTS` variable which users can use to customize the look and feel.

Updating the plugin to respect fzf's variables would be a major improvement.

**Comment by joshskidmore** [comment]
In terms of #31, the sourcing of the plugin within OMZ is separate from this request.

There are a various number of FZF_*_OPTS variables, and in the official fzf widgets, they're included in different ways depending on the zsh widget. I'm not quite sure which options would make the most sense to support in this plugin. [This is a where](https://github.com/junegunn/fzf/blob/master/shell/key-bindings.zsh) the official fzf zsh key-specific options are used. Any suggestions are welcome.

For the time being, we do have a variable that can be used to include fzf options when using this plugin. You can set this by exporting the `ZSH_FZF_HISTORY_SEARCH_FZF_ARGS` parameter before sourcing (or having the zsh plugin magager) source the plugin. You can even pipe the official FZF options into using something like this:

```sh
export FZF_CTRL_R_OPTS="--bind=ctrl-o:accept"
export ZSH_FZF_HISTORY_SEARCH_FZF_ARGS="$FZF_CTRL_R_OPTS"

# using oh-my-zsh
plugins=(zsh-fzf-history-search)
```
