### ISSUE TITLE
invalid directive when trying to fetch commands with %T and similar strings

### ISSUE THREAD

**Issue by nitayk** [joshskidmore/zsh-fzf-history-search#34]
This issue started when I moved to a new computer (MacBook Pro Apple M2). 
When trying to fetch from the history command like:
`kcat -b broker -t topic  -C -Z -o beginning -f ' %k:%s\n'`
I get the following error:
`fzf_history_search:printf:35: %k: invalid directive`
and only left with part of the string in the terminal line:
`kcat -b broker -t topic  -C -Z -o beginning -f '`

The reason is that `printf` interprets the `%k` as a format specifier.

I am not sure why it only started now when I switched to a new computer, but though it will be a good idea to post about it here

Thanks

**Comment by joshskidmore** [comment]
@nitayk Could you test if this issue has been resolved with the current release?

**Comment by nitayk** [comment]
@joshskidmore Same error.
I will also share some screenshots which might make the issue clearer:
![Screenshot 2024-05-16 at 16 07 08](https://github.com/joshskidmore/zsh-fzf-history-search/assets/7082154/fbd50efb-2078-4850-ba93-1ba06dbdd4a3)
![Screenshot 2024-05-16 at 16 07 25](https://github.com/joshskidmore/zsh-fzf-history-search/assets/7082154/2d64e3ea-6757-420c-b6cf-b549bf66f196)

**Comment by nitayk** [comment]
Ok, it works!
Was my mistake before, i did manual pull before on the wrong plugin :)

Thanks!

**Comment by joshskidmore** [comment]
No worries. Definitely has happened to me too!
