### ISSUE TITLE
not copying the whole line after '%' character for some commands

### ISSUE THREAD

**Issue by alkeryn** [joshskidmore/zsh-fzf-history-search#35]
so if i try to chose some command that has the "%" character, anything after that will be cut for some reason.
some of those commands are
```bash
ffmpeg -f alsa -i default -flush_packets 1 $(date '+%d-%m-%y-%H_%M_%S').ogg
echo %hello%
```

if there is a command such as `echo %%foo%%bar%%` i'll get `echo %foo%bar%`

**Comment by joshskidmore** [comment]
I am unable to recreate this issue. Could you try again to see if the issue still exists?

This is searching with `%`:
![image](https://github.com/joshskidmore/zsh-fzf-history-search/assets/255734/caddfb06-e98c-4037-96fb-de5e9bb09d80)

And examples of selecting:
![image](https://github.com/joshskidmore/zsh-fzf-history-search/assets/255734/e7b47a6e-0a41-4910-85bb-9c9d234199d0)
![image](https://github.com/joshskidmore/zsh-fzf-history-search/assets/255734/06c662f9-b25a-4cbf-b6ed-7e50ad8a863e)

**Comment by joshskidmore** [comment]
On this machine, the plugin wasn't updated. This issue does exist, and I'll research.

**Comment by joshskidmore** [comment]
@alkeryn When you get a chance, could you test the latest release?

**Comment by alkeryn** [comment]
hey!
thanks for the fix!
i can confirm that the issue is solved on my end, thank you ! :)
