### ISSUE TITLE
does zsh have this built in now?

### ISSUE THREAD

**Issue by p1r473** [joshskidmore/zsh-fzf-history-search#38]
hey,
is this now built into zsh? I can ctrl+R and seem to get a fzf empowered history search with this disabled

**Comment by joshskidmore** [comment]
I temporarily moved my .zshrc file and opened a new terminal. It seems zsh now has a helper to create your .zshrc file. Even when allowing history to be saved, `ctrl-r` was bound to the original default `bck-i-search` and not anything with fzf. Could you have a previous .zshrc somehow loaded?

**Comment by p1r473** [comment]
hey @joshskidmore I just played around with it and can confirm this is now backed into oh my zsh's built in fzf plugin
Is there any difference between yours and this one?
https://github.com/unixorn/fzf-zsh-plugin?tab=readme-ov-file

**Comment by laur89** [comment]
Perhaps people are just installing fzf's zsh bindings via
```sh
source <(fzf --zsh)
```

and getting confused?
